version: "3"

services:
  stream-site:
    build: ./public-site
    image: stream-site
    container_name: stream-site
    command: yarn develop -- -H 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./public-site:/usr/app
      - /usr/app/node_modules
